### ISSUE TITLE
improvement suggestion for the Streamlit/openai app 

### ISSUE THREAD

**Issue by Clement-Lelievre** [ArjanCodes/examples#25]
hi Arjan,

In you Streamlit/openai [app](https://github.com/ArjanCodes/examples/blob/main/2023/openai/explainer.py) you may benefit from using more params the openAI API offers. 
For example, because the first question ("which programming language?") expects a single word, you can use [max_tokens ](https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens) to enforce a single-word answer. Likewise, logit_bias might help. Also, for a nicer UX you can [stream](https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream) the model's completion.

Happy to share an example,
Best,

Clem

**Comment by egges** [comment]
Great suggestions! I'll think about covering these things in a follow-up video. I'd prefer to keep this example as is to make sure it still makes sense together with the already published video.
