### ISSUE TITLE
examples/2024/golroast/after /game.py wont work with python 3.11

### ISSUE THREAD

**Issue by dbw16** [ArjanCodes/examples#38]
https://github.com/ArjanCodes/examples/blob/69c087be3f87c360b168df11cf78c08eb3ebaecc/2024/golroast/after/pyproject.toml#L8
and
https://github.com/ArjanCodes/examples/blob/69c087be3f87c360b168df11cf78c08eb3ebaecc/2024/golroast/after/pyproject.toml#L8
say that this code should work with python 3.11^ but the syntax here https://github.com/ArjanCodes/examples/blob/69c087be3f87c360b168df11cf78c08eb3ebaecc/2024/golroast/after/game.py#L4
 requires 3.12. 
Tripped me up for a couple mins when i went to play around with the code.

I dont normally use poetry so could be wrong here.

**Comment by egges** [comment]
Well spotted - fixed!
