### ISSUE TITLE
Unexpected Error in py_wanderer.plotter

### ISSUE THREAD

**Issue by iand66** [ArjanCodes/examples#48]
After a simple c&p from GH repo when streamlit run simple_plot.py

  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\py_wanderer\plotter.py", line 21, in plot_maze_with_paths
    cmap = cm.get_cmap("tab20")
           ^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'

**Comment by egges** [comment]
Thanks for posting the issue. This seems to be an issue with the py_wanderer package and not with the code example, so I'm going to close this one.
