### ISSUE TITLE
Automate Releases to PyPI: grep command for latest version not working correctly

### ISSUE THREAD

**Issue by mpvanderschelling** [ArjanCodes/examples#56]
## The problem

Retrieving the latest_previous_version in the [`release.yaml`](https://github.com/ArjanCodes/examples/blob/main/2024/publish_pypi/release.yaml) from the 'GitHub Actions for Python Packages: How to Automate Releases to PyPi' code with the grep command will retrieve the first version released and not the latest.

https://github.com/ArjanCodes/examples/blob/0b8c8ab74908be5ed9239fcdaed875548d3f595c/2024/publish_pypi/release.yaml#L51

## Minimal example

I'm testing this with my own package `f3dasm`:

```
response=$(curl -s https://pypi.org/pypi/f3dasm/json || echo "{}")
latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
echo $latest_previous_version
```
Will yield `0.0.1`, which is the first version released and not the latest (`1.5.5` at the time of writing). See [here](https://pypi.org/pypi/f3dasm/json)

## Possible solution

I changed the grep line to the following in my own code:
```
latest_previous_version=$(echo $response | awk '/"releases":/ {flag=1} flag' | grep -oP '"\d+\.\d+(\.\d+)*"' | tr -d '"' | sort -rV | head -n 1)
```

I'm no expert and this; this searches for every "x.x.x" string (where x = digit) after "releases": has been found

**Comment by ABDreos** [comment]
Thanks for the issue! Would you like to contribute to the repo? If so, you will be mentioned as an contributor :)
